### ISSUE TITLE
[request] option to start recording video messages with the rear camera

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#1]
Hello,

Thank you for enabling the issues tracker.

I really like the idea of a fork of the official client with some small additions to improve the experience.

One option I really appreciate in Telegram X and I would love to see on Forkgram is the option to start recording video messages with the rear camera, which is in my experience what I want to use from the beginning of the recording most of the times. How would you feel about such an option?

**Comment by 23rd** [comment]
Thanks for request.
It didn't look very complicated to implement.

**Comment by RememberTheAir** [comment]
Thank you!

Just tried it out in 5.4.0.7, but it seems like I can't switch to Video Messages anymore. Shortly tapping on the voice message icon doesn't switch to Video Messages

**Comment by 23rd** [comment]
Sorry, you need to enable in-app camera.

**Comment by RememberTheAir** [comment]
Oh yeah, you are right. It works!
