### ISSUE TITLE
[feature request] show profile picture upload date

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#10]
Similarly to how already happens on Telegram Desktop and Telegram X, it would be nice to be able to see profile picture's upload date when opening someone's (or my) profile pictures

**Comment by RememberTheAir** [comment]
Closed with version 5.9.0 I guess

**Comment by 23rd** [comment]
Can you check this out for the latest version?

**Comment by foad-heidari** [comment]
Hello.
Does telegram give the user profile picture upload date?

**Comment by 23rd** [comment]
Yes it does.

**Comment by foad-heidari** [comment]
@23rd any link or reference? 🙏

**Comment by 23rd** [comment]
> any link or reference?

Any instance of `class UserProfilePhoto` has `photo_id` field. With that field you can get `class Photo` with `date` field.

See `TLRPC.java`.

**Comment by foad-heidari** [comment]
@23rd thanks for the help!
