### ISSUE TITLE
Application name is 'org.telegram.messenger.ForkApplicationLoader' in F-Droid version

### ISSUE THREAD

**Issue by niobium93** [forkgram/TelegramAndroid#103]
`org.telegram.messenger.ForkApplicationLoader` shows up as the name of the app in the F-Droid version. This was previously reported in #97 but that was closed erroneously. The apk file from the GitHub releases works fine.

**Comment by github12101** [comment]
Agreed, I just installed it from F-Droid and that's what name is.

**Comment by niobium93** [comment]
Fixed with 9.0.2.0!
