### ISSUE TITLE
Playstore release

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#107]
Make this amazing app available in google playstore

**Comment by 23rd** [comment]
Never will be.
You are free to make a fork of this Fork Client, name it differently, refer to this repository in the description and publish by yourself. But I will never create a Google account for publishing this project in the Google Playstore, sorry.

**Comment by ghost** [comment]
> Never will be.
> You are free to make a fork of this Fork Client, name it differently, refer to this repository in the description and publish by yourself. But I will never create a Google account for publishing this project in the Google Playstore, sorry.

Oh, I'm Sorry!

I don't know you are a degoogled❤️ user.
Kudos🎉 Man and Thank you for this amazing Telegram client.
