### ISSUE TITLE
[Feature Request] Hide animated emoji tab

### ISSUE THREAD

**Issue by lowend-user** [forkgram/TelegramAndroid#113]
Let me first thank you for all the work and effort you put in this project, the quality is astonishing. I'd like to make a donation but I couldn't find any info about it, so please let me know how I can support you.

So, **animated emojis** are premium feature I cannot even use, but their selector covers 80% of the entire emoji tab, thus:
1) making navigation through normal emojis much harder;
2) consuming RAM and resources for useless animations I cannot disable;
3) destroying my mental health with cringe cartoony overly joyful images that only aggravate my cognitive dissonance and detachment from reality.

![IMG_20221126_142513_682](https://user-images.githubusercontent.com/119114245/204091351-ddf9bce2-3ca1-4f07-bcf9-492a684075d9.jpg)

Being able to disable this tab and restore the old design, thus sending these forcefully smiling demons back to Oblivion, would **benefit usability and performance** and would probably get you a nomination for the **Nobel Peace Prize**.

Thank you for your patience

([Plusmessenger](https://plusmessenger.org/links)  implemented this but I couldn't find the code anywhere)

**Comment by lowend-user** [comment]
I did some research and I discovered [Nekogram](https://gitlab.com/Nekogram/Nekogram) implements this feature by default

**Comment by 23rd** [comment]
Added a new option.

**Comment by lowend-user** [comment]
> Added a new option.

Oooh it's beautiful! Thank you so much!!!
Would it be possible to also have the old UI, like in Nekogram? Like this
![IMG_20221210_225745_911](https://user-images.githubusercontent.com/119114245/206876800-6be2ff21-06f7-43fd-82cf-e0a5a2d7fa07.jpg)
Because it's still a bit uncomfortable to navigate through the emoji panel with that micro-bar. If not don't worry, what you did was already a great improvement.
I can't thank you enough

**Comment by lowend-user** [comment]
Update: since v9.4 the new interface makes the last requeste obsolete, now it's fully usable, like it was before the dark times.
Thank you <3
