### ISSUE TITLE
9.2.0.0, 9.2.1.0 and 9.2.2.0 crash while opening stickers, emojis and gif menu

### ISSUE THREAD

**Issue by Plagouille** [forkgram/TelegramAndroid#115]
Versions 9.2.0.0, 9.2.1.0 and 9.2.2.0 crash when I open the menu to add a stricker, an emoji or a gif.

I get back to 9.1.6.0 (29290).

How can I help to solve this issue ?

**Comment by hmtheboy154** [comment]
same problem here

**Comment by Plagouille** [comment]
Official Telegram client 9.2.2.0 from telegram.org works.

**Comment by hmtheboy154** [comment]
> Official Telegram client 9.2.2.0 from telegram.org works.

Do you have Premium ? I noticed that ever since my Premium is expired my stickers/emojis box is working again

**Comment by Plagouille** [comment]
Yes I have premium. You probably discovered what is the problem. I will wait the next version and test it. I hope that will be ok.

**Comment by hmtheboy154** [comment]
guess we can pointed correctly where the problem is
However I am not the dev

**Comment by 23rd** [comment]
https://github.com/Forkgram/TelegramAndroid/releases/tag/9.2.2.1

**Comment by Plagouille** [comment]
Looks like 9.2.2.1 is working. Thanks !
I let you know if anything get wrong.
