### ISSUE TITLE
Changing code (PIN) 

### ISSUE THREAD

**Issue by Plagouille** [forkgram/TelegramAndroid#119]
Not possible to change the code PIN. When the code is entered on settings, security, code, the screen does not change to settings. Blocked on the PIN screen. Only back is possible.

**Comment by Plagouille** [comment]
I am on last 9.3.0.0 but I had the same issue on previous version 9.2.2.1 (corrected for premium).

**Comment by BDGreyson** [comment]
Issue still persists in 9.5.2.0 (32080) direct arm64-v8a

I do know the PIN an can unlock Forkgram, but getting into the PIN-settings is impossible.

**Comment by BDGreyson** [comment]
Issue has been fixed in https://github.com/forkgram/TelegramAndroid/issues/185

I guess this could be closed then, as well?

**Comment by Plagouille** [comment]
It works now on the last version 9.9.2.0. Thank you verry much !
