### ISSUE TITLE
App crashes upon creating new Secret chat

### ISSUE THREAD

**Issue by contracourse** [forkgram/TelegramAndroid#122]
When I want to start a new secret chat on the main page by opening the hamburger menu, the app crashes.

**Comment by urystem** [comment]
For Me too. Also app named to "org.telegram.messenger.ForkapplicationLoader". My phone android 13, Custom ROM.

**Comment by ppxv** [comment]
Same problem

**Comment by keylogthis** [comment]
I just installed it, and am also experiencing this issue on A13, the other popular FOSS client works.

**Comment by iiwwnnaa** [comment]
Same on A13

**Comment by iiwwnnaa** [comment]
This problem fixed on ForkClient 9.5.3.1
