### ISSUE TITLE
please add an option to forkgram so that we can hide username and phone number in telegram settings

### ISSUE THREAD

**Issue by 0xRustlang** [forkgram/TelegramAndroid#126]
Hello

I use your app to create learning materials for my students.

It is great that your client doesn't show username and phone number in drawer menu.

But it still shows it in telegram settings.

May you please add an option so that I can hide them also?

You can put them in three dot menu of settings or add an option to hide them in forkgram settings section.

This will be great, If may please make it happen. 

Thank you so much.

I also use your app for my kids and the disable global search toggle and some other options are great.

**Comment by 23rd** [comment]
There is the "Hide Sensitive Data" option in Fork Settings.

**Comment by 0xRustlang** [comment]
> There is the "Hide Sensitive Data" option in Fork Settings.

Oh, I see.
Thank you so much.
