### ISSUE TITLE
Option to always hide forward information (name) 

### ISSUE THREAD

**Issue by woj-tek** [forkgram/TelegramAndroid#133]
While forwarding a message there is an option to hide/remove forwarding details (name). It would be awesome to have option to remove it always by default without having do to it manually each time. and it could also work / be enable while forwarding to multiple contacts at once (in that case there is no option to hide the information altogether)

**Comment by 23rd** [comment]
Give a try for the "Replace original Forward" option in fork settings.

**Comment by woj-tek** [comment]
I had it enabled but somehow I missed it in the context menu, thanks! :-)
