### ISSUE TITLE
[feature request] hold on a mention pop-up to mention by name

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#14]
It would be nice to be able to hold on a mention suggestion (that appear when you write a "@") to mention the user by their name even when they have an username, similarly to how it happens on TGX

**Comment by 23rd** [comment]
Can you please provide a video of this feature?

**Comment by RememberTheAir** [comment]
Yes, https://streamable.com/hqpnv

**Comment by 23rd** [comment]
Does this have to be configured separately from the Fork Settings?

**Comment by RememberTheAir** [comment]
Hmm, I don't think there need to be a setting for that, since there's no action binding for that popup
