### ISSUE TITLE
[bug] archived chats are frequnetly unarchived when new messages arrive

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#15]
So, I've started to notice this weird behavior some weeks/months ago: sometimes some archived chats were being unarchived when a new message arrives. The issue is surely client side, because they weren't being unarchived on other clients too, where everything was working correctly. Using the "reload conversation" option in the debug menu would fix that, and re-archive the chats that were being unarchived.

A few weeks back it was happening so often that I had to try to do something. I've initially tried to clear the database, no luck. Logged out, no luck. Reinstalling forkgram actually fixed the problem for some days, then it started to happen again.

It is a really weird bug, and since forkgram doesn't have this much tweaks about the chats list, I assumed it might be an issue of the normal app too, so I tried to switch to it for some days. And surprisingly chats never got unarchived. So I suppose it's an issue with forkgram.

Unfortunately I don't know what other details to provide, it has been happening since a few releases. Probably after the update that came before scheduled messages

**Comment by RememberTheAir** [comment]
Update on this: I'm using v. 5.11.0.2 with the default quickshare chats sorting, which seems to fix the issue. Anyway, sometime the app "forgets" the last chunk of my **archived** pinned chats, which appear as not pinned (but still in the archive) (no issues on desktop so it's not related to the API). I have to "resync dialogs" from the debug menu to fix them and have them pinned again - but doing so brings back the old problem of random archived chats being unarchived. When this happens I have to use a few time the "resync dialogs" option from the debug menu to fix the issue. it goes on for some hours and then my archived chats don't get unarchived again - until the app forgets again my last chunk of archived pinned chats, which appears to happen once every 2/3 days. Really weird

A little step-by-step scenario:

1. everything is okay
2. I notice that the last part of my **pinned archived** chats got unpinned (specifically, all the pinned chats **after the 50th pinned chat**)
3. the "re-sync dialogs" option from the debug menu fixes the issue and pins them again
4. after the re-sync, some of my archived chats get unarchived and I have to re-sync the dialogs from the debug menu to move them to the archive again
5. repeat 4 for a few hours because other chats will get unarchived as new messages arrive
6. no issues for a few days
7. point n° 2 happens again - repeat from there

**Comment by RememberTheAir** [comment]
Another detail about pinned archived chats being unpinned from time to time (n° 2 on the step-by-step list of my previous comment): the archived pinned chats that get unpinned are all the chats after the **50th** pinned chat, which is a weirdly round number. I've edited the list in my previous comment accordingly

**Comment by RememberTheAir** [comment]
> Another detail about pinned archived chats being unpinned from time to time (n° 2 on the step-by-step list of my previous comment): the archived pinned chats that get unpinned are all the chats after the 50th pinned chat, which is a weirdly round number. I've edited the list in my previous comment accordingly

Upstream issue too

**Comment by 23rd** [comment]
Do you mean the official client?

**Comment by RememberTheAir** [comment]
Yes - but just the issue with pinned archived chats being unpinned. Archived chats being unarchived doesn't happen on the vanilla app

**Comment by RememberTheAir** [comment]
Chats now are no longer unarchived, as of version 5.13.0 (18280). It still happens that sometimes, my archived pinned chats get unpinned randomly but that's an issue of the official app too. I will close this issue as soon as 5.13.0 gets merged
