### ISSUE TITLE
App crashes using (live) location

### ISSUE THREAD

**Issue by siggib4** [forkgram/TelegramAndroid#151]
The app crashes (needs to be aborded) once I try to let me show the live location of a received or sent live location. It crashes 9 of 10 times,  so quite reproduceable. Sometimes it happens also if I let me show a location lnot a live location).

**Comment by 23rd** [comment]
Does this happen in the Foss version of Telegram?

**Comment by siggib4** [comment]
Yes, exactly the same happens with Telegram FOSS.

**Comment by siggib4** [comment]
Wipe Cache Partition solved it for me, for Telegram FOSS and Forkgram. :D

Sorry for confusion. And thx for the quick reply.
