### ISSUE TITLE
[BUG] Cannot register 

### ISSUE THREAD

**Issue by HarriBuh** [forkgram/TelegramAndroid#159]
..as the App keeps sending SMS to my "other device", which does ironically NOT exist at all. I guess this is the reason why I'm unable to both proceed and finish the registration process.

**Comment by DeadSecTr** [comment]
Only with the official app you can register

**Comment by HarriBuh** [comment]
What's the point in using the fork then? I remember that account registration with any fork wasn't an issue before. Is this permanent?

**Comment by DeadSecTr** [comment]
The fork is foss...thats the point! Install the official,register/login....then install the fork...delete the official one

**Comment by HarriBuh** [comment]
That is certainly not the point, if I had to use the official app beforehand..anyway, it seems if there wouldn't be another way any longer, so..
