### ISSUE TITLE
[Bug] Package name shown instead of app name

### ISSUE THREAD

**Issue by nandgator** [forkgram/TelegramAndroid#160]
On work profile this is how it shows:

![Screenshot_20230713_075100_One UI Home_1.jpg](https://github.com/forkgram/TelegramAndroid/assets/38415384/84d8ca15-5662-4e1e-b8fa-110cd9f83748)

**Comment by matt-rgx** [comment]
i confirm, here is the same for me on latest (v9.7.2 - 37050)

**Comment by TakiShiwa** [comment]
Yup, I confirm

**Comment by DeadSecTr** [comment]
Till today is the name weird....why? ![Screenshot_2023-08-03-01-52-58-25_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/forkgram/TelegramAndroid/assets/90558189/7f4e0c5e-467c-4280-a8db-fb40610264f1)

**Comment by TakiShiwa** [comment]
Try downloading the app from GitHub, uninstall the f-droid one

**Comment by TakiShiwa** [comment]
> Try downloading the app from GitHub, uninstall the f-droid one

GitHub one is fixed

**Comment by matt-rgx** [comment]
> > Try downloading the app from GitHub, uninstall the f-droid one
> 
> GitHub one is fixed

But after installing the one from github, how do de manage to keep it up to date ?

**Comment by matt-rgx** [comment]
> > > Try downloading the app from GitHub, uninstall the f-droid one
> > 
> > 
> > GitHub one is fixed
> 
> But after installing the one from github, how do de manage to keep it up to date ?

Actually i've checked and the latest from github (9.7.4) is the same as the latest on f-droid (9.7.4) so i don't know how did you get the fix for that ?

Thanks

**Comment by TakiShiwa** [comment]
# This is how you update it

![IMG_20230803_151833.jpg](https://github.com/forkgram/TelegramAndroid/assets/137756384/63c706b9-fe90-4d90-b50a-5624537c65bd)

# And this is my pakage name etc.

![Screenshot_2023-08-03-15-17-56-39_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/forkgram/TelegramAndroid/assets/137756384/1f35c64c-228b-4172-bcd3-c6bb788cfe35)

**Comment by TakiShiwa** [comment]
> > > > Try downloading the app from GitHub, uninstall the f-droid one
> > > 
> > > 
> > > GitHub one is fixed
> > 
> > But after installing the one from github, how do de manage to keep it up to date ?
> 
> Actually i've checked and the latest from github (9.7.4) is the same as the latest on f-droid (9.7.4) so i don't know how did you get the fix for that ?
> 
> Thanks

Download it and install it
From releases section

**Comment by matt-rgx** [comment]
> > > > > Try downloading the app from GitHub, uninstall the f-droid one
> > > > 
> > > > 
> > > > GitHub one is fixed
> > > 
> > > 
> > > But after installing the one from github, how do de manage to keep it up to date ?
> > 
> > 
> > Actually i've checked and the latest from github (9.7.4) is the same as the latest on f-droid (9.7.4) so i don't know how did you get the fix for that ?
> > Thanks
> 
> Download it and install it From releases section

ok thanks i will try that. Then i will have to blacklist Forkgram on f-droid to avoid get in trouble ? Am i right ?

**Comment by TakiShiwa** [comment]
> > > > > > Try downloading the app from GitHub, uninstall the f-droid one
> > > > > 
> > > > > 
> > > > > GitHub one is fixed
> > > > 
> > > > 
> > > > But after installing the one from github, how do de manage to keep it up to date ?
> > > 
> > > 
> > > Actually i've checked and the latest from github (9.7.4) is the same as the latest on f-droid (9.7.4) so i don't know how did you get the fix for that ?
> > > Thanks
> > 
> > 
> > Download it and install it From releases section
> 
> ok thanks i will try that. Then i will have to blacklist Forkgram on f-droid to avoid get in trouble ? Am i right ?

When I installed the GitHub one installed as a separate app , and didn't updated the existing f-droid one,
So I uninstalled the f-droid one.

**Comment by matt-rgx** [comment]
> > > > > > > Try downloading the app from GitHub, uninstall the f-droid one
> > > > > > 
> > > > > > 
> > > > > > GitHub one is fixed
> > > > > 
> > > > > 
> > > > > But after installing the one from github, how do de manage to keep it up to date ?
> > > > 
> > > > 
> > > > Actually i've checked and the latest from github (9.7.4) is the same as the latest on f-droid (9.7.4) so i don't know how did you get the fix for that ?
> > > > Thanks
> > > 
> > > 
> > > Download it and install it From releases section
> > 
> > 
> > ok thanks i will try that. Then i will have to blacklist Forkgram on f-droid to avoid get in trouble ? Am i right ?
> 
> When I installed the GitHub one installed as a separate app , and didn't updated the existing f-droid one, So I uninstalled the f-droid one.

yep i do the same but sometimes f-droid try to update app that are not installed via f-droid.

**Comment by TakiShiwa** [comment]
> > > > > > > > Try downloading the app from GitHub, uninstall the f-droid one
> > > > > > > 
> > > > > > > 
> > > > > > > GitHub one is fixed
> > > > > > 
> > > > > > 
> > > > > > But after installing the one from github, how do de manage to keep it up to date ?
> > > > > 
> > > > > 
> > > > > Actually i've checked and the latest from github (9.7.4) is the same as the latest on f-droid (9.7.4) so i don't know how did you get the fix for that ?
> > > > > Thanks
> > > > 
> > > > 
> > > > Download it and install it From releases section
> > > 
> > > 
> > > ok thanks i will try that. Then i will have to blacklist Forkgram on f-droid to avoid get in trouble ? Am i right ?
> > 
> > 
> > When I installed the GitHub one installed as a separate app , and didn't updated the existing f-droid one, So I uninstalled the f-droid one.
> 
> yep i do the same but sometimes f-droid try to update app that are not installed via f-droid.

Turn off autoupdate for forkgram,
Btw use droidify

**Comment by nandgator** [comment]
But why won't the fix work on f-droid? Because it doesn't allow editing release?

The next version would certainly contain the fix, am I right?

**Comment by et-ness** [comment]
Duplicate #110 please close, there are too many issues

**Comment by matt-rgx** [comment]
is there any chance to solve this one some day ?
thx

**Comment by nandgator** [comment]
Probably if https://github.com/forkgram/TelegramAndroid/pull/199 gets merged.

**Comment by nandgator** [comment]
Closing in favour of #110, #180, #227, #234.

**Comment by woj-tek** [comment]
> Probably if #199 gets merged.

@yozachar is there any chance to merge above PR?

**Comment by nandgator** [comment]
> > Probably if #199 gets merged.
> 
> @yozachar is there any chance to merge above PR?

I'm sorry, I'm not the maintainer.
