### ISSUE TITLE
People nearby feature not working

### ISSUE THREAD

**Issue by shom13** [forkgram/TelegramAndroid#166]
I just installed forkgram and i am trying to use the people nearby feature that i used to view om telegram foss. But for some reason it cannot access location although i have enabled the sharing location permission. Any ideas where am i going wrong here. Thanks in advance

**Comment by rodrigoaguilera** [comment]
I'd say this is a duplicate of #144

**Comment by shom13** [comment]
Ok downloaded it directly from github seems to have resolved the issue. Thanks
