### ISSUE TITLE
App crashes upon creating new Secret chat.

### ISSUE THREAD

**Issue by farline99** [forkgram/TelegramAndroid#167]
Duplicate of #122. 9.7.4 version.

**Comment by 23rd** [comment]
Can't reproduce.

**Comment by farline99** [comment]
https://github.com/forkgram/TelegramAndroid/assets/100877226/6e04b847-6d65-44d2-b013-c057a63f2597

![98146e8c-8d66-41f1-ab0c-109e9d1927b9](https://github.com/forkgram/TelegramAndroid/assets/100877226/16830399-73ed-4a64-b009-6a3a729854a7)

LineageOS 19.1 + microG (MinMicroG).

**Comment by contracourse** [comment]
I think its an issue solely on grapheneOS. I've the same problem.

**Comment by farline99** [comment]
> I think its an issue solely on grapheneOS. I've the same problem.

Definetly not. Same here with LineageOS 🙂

**Comment by DeadSecTr** [comment]
Same here with ColorOS Android 13 No Root

**Comment by farline99** [comment]
Fixed for me on 9.7.7. Thank you for being such a good maintainer ❤️
