### ISSUE TITLE
[bug?] fast forward: albums are not forwarded as albums

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#17]
### Steps to reproduce
1. forward an album using the "fast forward" option

### Expected

The album is forwarded as an album

### Actual

Each media in the album is forwarded alone

**version:** 5.11.0.2

I'm not sure this is worth to fix, if too complex

**Comment by 23rd** [comment]
This is a known problem. =(
Maybe sometimes I'll fix it.

**Comment by RememberTheAir** [comment]
Fixed on 7.2.1.7
