### ISSUE TITLE
[Feature request] Hide stories

### ISSUE THREAD

**Issue by lowend-user** [forkgram/TelegramAndroid#172]
It would be great to have a toggle switch to disable/hide the new "Stories" feature.

Aligning with my past requests, this one aims at maintaining the user experience as simple and functional as possible, avoiding useless clutter on screen and unnecessary consumption of resources, especially for low end devices (like the 2016 phone I'm using).

Thank you in advance :)

**Comment by lowend-user** [comment]
I'm dumb I hadn't look well enough, there's already the option. Sorry

**Comment by 0slav** [comment]
@lowend-user Where did you find that option? I can't seem to find it in 9.7.7 from f-droid.

**Comment by xgaia** [comment]
I didn't find the option too :cry:

**Comment by Idesmi** [comment]
There is no option yet. Nekogram implemented this with https://gitlab.com/Nekogram/Nekogram/-/commit/68fa68088595e48f7a17a9f8300d310010ec89c2
