### ISSUE TITLE
Fast-forward doesn't put messages in the wanted topic

### ISSUE THREAD

**Issue by signed-log** [forkgram/TelegramAndroid#178]
## Steps to reproduce :

- Create a group and enable topics
- Create a topic (b) and close the original one (a)
- Use the fast-forward menu to forward a message to the newly created topic (b)

## Expected :

Message gets sent to b

## Happening :

Message is still sent to a

## Hardware :

Oppo CPH2305
Android 13
Fork Client 9.7.4.0

**Comment by 23rd** [comment]
I believe should be better now.

**Comment by signed-log** [comment]
> I believe should be better now.

Updated to 9.79, still not forwarding correctly

**Comment by 23rd** [comment]
There is 9.9.0.0.

**Comment by signed-log** [comment]
F-Droid is WAY out of date then... 9.79 is the last one over there

**Comment by signed-log** [comment]
F-Droid is WAY out of date then... 9.79 is the last one over there

**Comment by signed-log** [comment]
Fixed with 9.9.2.0
