### ISSUE TITLE
[bug] fast forward's "copy link" button doesn't copy any link

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#18]
### Steps to reproduce

1. select a message from a private/public chat
2. use the "fast forward" from the action bar
3. tap on "copy link"

### Expected

The link to the message is copied to the clipboard

### Actual

The clipboard is emptied or an empty string is copied

**Version:** 5.11.0.2

**Comment by 23rd** [comment]
If more than one message is selected, which message's link should be copied to?

**Comment by RememberTheAir** [comment]
Mmmh, I don't know. I think you can make it copy nothing or the first message link

**Comment by 23rd** [comment]
Should be fixed?

**Comment by RememberTheAir** [comment]
Mmmh, if it's not too hard it would be nice to have it copy an url at least only when one message is selected

**Comment by 23rd** [comment]
But you can already copy a link to one selected message, it just works (if I understand it correctly) only for supergroups and channels.

**Comment by RememberTheAir** [comment]
> Mmmh, if it's not too hard it would be nice to have it copy an url at least only when one message is selected

Tested this and it works like that, at least now. Also for private channels. Maybe, when more than one message are selected and the "copy link" option from the "anonymous forward" sheet is used, a toast notification can be displayed saying you have to select only one message

**Comment by RememberTheAir** [comment]
I'm closing as how it works now is acceptable
