### ISSUE TITLE
Forward messages doesn't work in Secret chats

### ISSUE THREAD

**Issue by serrq** [forkgram/TelegramAndroid#182]
I cannot forward messages to "saved messages" because "forward" is untouchable (grey).

9.7.8.0

**Comment by 23rd** [comment]
The same behaviour as in the official client.

**Comment by serrq** [comment]
> The same behaviour as in the official client.

The question is: can you modify this behavior?
Because I need of forward even in encrypted chats.

**Comment by 23rd** [comment]
In what way do you envision it? How should messages from your conversation partner look in your Saved Messages?

**Comment by serrq** [comment]
> In what way do you envision it? How should messages from your conversation partner look in your Saved Messages?

Both cases I need. Or even external (Android sharing hub) like SimpleX Chat does.

I mean forward to people or saved messages (to myself).

**Comment by 23rd** [comment]
I'm not sure you understand how encrypted chats work. What you're asking for requires downloading any content in the encrypted message and resending it again (it is a special pain when you have files up to 4GB), but to a "normal" unencrypted chat. In that vein, I don't see the point of implementing this feature. I believe you can find a better client with a matching feature.

**Comment by serrq** [comment]
Normally I use SimpleX Chat that it is 100% encrypted. No "secret" chats. Just all encrypted.

**Comment by 23rd** [comment]
Cool, never heard before. 👍

**Comment by serrq** [comment]
Mmm. Spam immunity with SimpleX. No phone number. No email. No IDs. Contacts connections are made by disposable links. All encrypted.

**Comment by serrq** [comment]
You can find it in F-droid (it has also its own repo).

**Comment by AlexBar** [comment]
Desktop version of forkgram https://github.com/forkgram/tdesktop has function "Share" to send a copy of message from chats where forwarding is not allowed. Is it possible to implement the same behaviour?
