### ISSUE TITLE
[feature request] option to delete all my messages in a group chat

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#19]
I've seen people asking for this fairly often, and I think it would be nice to be able to delete your digital footprint from a group chat without having to find and delete all your messages. Maybe an option in the three-dots menu in the chat info's screen?

**Comment by 23rd** [comment]
Yeah, I've heard a lot of requests for this feature. But at first sight it's not an easy task, especially with such a mushy code base, as in the Telegram for Android, so I'm not sure when I can find the time for this. =(

**Comment by RememberTheAir** [comment]
I see, no problem

**Comment by RememberTheAir** [comment]
Will close this issue as there's no point in keeping this open, since you're aware of the request but lack the time to work on it
