### ISSUE TITLE
Remove "Telegram premium" sponsored messages

### ISSUE THREAD

**Issue by MaxLPM** [forkgram/TelegramAndroid#190]
These "sponsored messages" (see image below) are really annoying, is there any way to remove them?
https://github.com/forkgram/TelegramAndroid/assets/138196893/f3113727-ef2d-4c7f-8c85-1ac5a4ce5312
They seem to appear at random in channels and in comments

**Comment by 23rd** [comment]
```
3.3. If your app allows accessing content from Telegram channels,
you must include support for official sponsored messages
in Telegram channels and may not interfere with this functionality.
```
https://core.telegram.org/api/terms#3-advertising-amp-monetization
