### ISSUE TITLE
[Feature Request] Send and view large photos (2560px)

### ISSUE THREAD

**Issue by AgFlore** [forkgram/TelegramAndroid#192]
From early 2023, telegram's photo size limit has been doubled to 2560px. 
In tgdesktop, one can enable `"Send large photos (Increase the side limit on compressed images to 2560px.)"` and enjoy the feature, but on other platforms (including forkgram?) users are still met with the 1280px limit.

**Comment by 23rd** [comment]
Please check the settings in the latest version.
