### ISSUE TITLE
Qrcode square not staying center and not scan qrcode

### ISSUE THREAD

**Issue by DrVektor** [forkgram/TelegramAndroid#202]
i am using lineageos on redmi note 5a prime. forkgram. I tried to introduce my device to desktop telegram but qrcode scanner never does it. qr code reading frame can't stay in place. When I hold the phone upright, it slides down and is never positioned exactly in the center. When I somehow show the qr code, it never reads it.  Thank you.

**Comment by 23rd** [comment]
Did you test the official client?

**Comment by DrVektor** [comment]
@23rd no unfortunatelly. But i thought that too. Than you i will test it. Update: forkgram is good again. Telegram never even gets to the stage of sending code. ☹
