### ISSUE TITLE
Forkgram Desktop version doesn't support this proxy type

### ISSUE THREAD

**Issue by usergitalberto** [forkgram/TelegramAndroid#223]
In some links dedicated to add a new proxy isn't possibile to use due to an error message:

_"Your Forkgram Desktop version doesn't support this proxy type or the proxy link is invalid. Please update Forkgram Desktop to the latest version."_

Below is an example link:

https://t.me/proxy?server=cloudflare.com.nokia.com.co.uk.do_yo.want_to.clash_with.this.www.microsoft.com.there_is_no.place_like.localhost.www.bing.com.count_with_me.cyou.net.now_sudo.rm.again_to_fight.everyone.i_am.the_internet.colam-bonaza.sbs.&port=4550&secret=AAAAAAAAAAAAAAAAAAAAAGQ=

**Comment by 23rd** [comment]
Not related to Android repository.
