### ISSUE TITLE
No "Edit Profile"?

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#226]
Is the "Edit Profile" lacking?
There is no way to see/change username and phone number in the mobile client (unlike in desktop client).

Saw this text on the main page: "Menus to edit username/bio/name moved in the debug menu (two long tap on version section)",
and tried to find this "Edit Profile" thing in the debug menu, but it's not there either, so this text is wrong.

Could you add "Edit Profile"?

**Comment by 23rd** [comment]
Hold the three-dot button or just turn off the “Hide sensitive data” setting.

**Comment by ghost** [comment]
Got it, thanks for the info.

Would be great to see thee instructions added to the main page / readme
