### ISSUE TITLE
[Feature Request] Cherrypick (copy) sticker size feature from nekogram 

### ISSUE THREAD

**Issue by zarEclEC** [forkgram/TelegramAndroid#23]
Here is the commit you need to cherrypick (and adapt to your client, I think) if you want to accept this feature request.
https://github.com/ArmeF97/Nekogram/commit/6054710c53fec1a9a2468e968d55b7707eb808a8

Basically it is the ability, client side, to resize stickers

Thanks

Maybe you are interested also in this
https://github.com/ArmeF97/Nekogram/commit/7919ec075a4a4ffdb2c43a9025aff3e6cebf79a0

**Comment by 23rd** [comment]
Are you sure I can cherry-pick commits from Nekogram?

**Comment by 23rd** [comment]
I mean, I can cherry-pick commits from the `Telegram-FOSS` almost without changing them.
But [this](https://github.com/ArmeF97/Nekogram/commit/6054710c53fec1a9a2468e968d55b7707eb808a8) commit has a lot of code from the Nekogram settings, and I should copy-paste it from there to my settings and that's the problem — this is not so "opensoursely" as I would like it to be.

**Comment by RememberTheAir** [comment]
Yeah someone should put some effort into it and port it to Forkgram's codebase and open a PR. Nekogram's code is licensed as GPL so as long as you give credit and publish it, you should be fine with the license. It would be nice to hear if the guys from Nekogram are okay with features-picking though, regardless of how the code is licensed

**Comment by zarEclEC** [comment]
If you don't want to copy the commit, you can try to develop this on your own, feel free to do what you like to do (if you are willing to accept this feature request)

**Comment by 23rd** [comment]
You can test a new feature from this link. I look forward to your feedback.

https://github.com/Forkgram/TelegramAndroid/suites/426318101/artifacts/1415836

**Comment by zarEclEC** [comment]
Amazing, good job!

Is it normal that the emoji selector is so small?

![photo_2020-01-29_16-00-03](https://user-images.githubusercontent.com/6240983/73367921-77cfb600-42b0-11ea-80f7-a9681609e963.jpg)

**Comment by 23rd** [comment]
This is not normal. =(

**Comment by RememberTheAir** [comment]
![image](https://user-images.githubusercontent.com/16143208/73368839-f842e680-42b1-11ea-859c-b796a49571a2.png)

Looks good on my phone, I have the stickers size set to 8. Maybe that's your normal height and the emoji search bar is taking up space?

**Comment by zarEclEC** [comment]
Fixed when I restarted the app... the issue does not show again...
