### ISSUE TITLE
Forkgram killing phone battery

### ISSUE THREAD

**Issue by ETJAKEOC** [forkgram/TelegramAndroid#236]
I installed Forkgram on my Moto G Pure running Lineage OS, twice now this application has left me stranded without a working phone because it ignores Android battery management software, killing my battery while my screen was off for hours on end when I never opened the application.

I have uninstalled the application and will never install it again due to this.

**Comment by 23rd** [comment]
> I have uninstalled the application and will never install it again due to this.

Thanks.
