### ISSUE TITLE
App crashes when forwarding a message to someone; but if that message is forwarded to more than one person does not, but even though the app crashes, the message *is* forwarded correctly

### ISSUE THREAD

**Issue by formula-spectre** [forkgram/TelegramAndroid#238]
i've been noticing this recently: if I forward a message to anyone, that be person, group, topic of a group, the app crashes, but, if I forward that message to multiple people/groups/topics, it does not. anyone else has this issue?  
- forkgram version: 10.9.10 (44640);
- android version: 14
- androidi rom: GrapheneOS (idk if it's relevant)

**Comment by kyoto44** [comment]
#231 related

**Comment by 23rd** [comment]
Will be fixed in the next coming version.

**Comment by formula-spectre** [comment]
seems that the issue is solved, BUT  
if I forward a message, with the pop up that allows you to search contacts, once I input any name/string, I can't click the contact(s) anymore
do I open a seprate issue?

**Comment by 23rd** [comment]
Hmm, why you can't? Can you share a screenshot?

**Comment by formula-spectre** [comment]
idk, I just can't click on the contact(s) bubbles, as for a screenshot, I don't think it's possible since it's a private acct. so I can't really divulge my contacts infos (GDPR rocks)

**Comment by formula-spectre** [comment]
as of writing this message, it seems that the problem does not manifest anymore; although I noticed a more intense battery usage, it does not belong in this issue.  
closing because it works as expected now
