### ISSUE TITLE
[Feature Request] Stop asking for Google when I don't have Google

### ISSUE THREAD

**Issue by zarEclEC** [forkgram/TelegramAndroid#24]
![photo_2020-01-29_22-13-53](https://user-images.githubusercontent.com/6240983/73397912-c72fd980-42e4-11ea-9fc5-d52a17919389.jpg)

I don't have any google app installed on my phone, not even google play service.
This message pops up every time I open forkgram.
Even if I say yes, nothing happens, I don't have Google.

Can't you add a if/else check?
If the user does not have google play service installed, the popup is useless, so simply don't show it

That way normal users won't notice any difference, only users like me will be grateful, thanks

**Comment by 23rd** [comment]
Do you still see this popup?
The ClassyShark3xodus app shows me 0 trackers for the latest version.

**Comment by RememberTheAir** [comment]
I just tried Forkgram on a Google-free phone and I do not have such issue. I think this can be closed

**Comment by zarEclEC** [comment]
Can you tell me in which commit this was implemented? So I make a pr in the official repo


The popup is gone so I close this, thanks

**Comment by RememberTheAir** [comment]
It's hard to tell since there's a lot of commits cherry-picked from Telegram-FOSS. The official repo will never merge such a pull request. It relies on Gooogle's FCM for push notifications, plus all the maps tiles and location stuff

**Comment by zarEclEC** [comment]
I never said to remove Google from official repo, I said to add an `if`
The `if` will check if the user have google, and if yes, show the popup in my first post. If not, no popup is showed.

We need only to add an `if`, not to edit the dependencies of the official app

**Comment by zarEclEC** [comment]
I have to re-open this because after I updated the app today, this was displayed:
![immagine](https://user-images.githubusercontent.com/6240983/83974016-77909880-a8ea-11ea-98a8-71b3610088ce.png)


As you can see, the popup is still shown

**Comment by zarEclEC** [comment]
Here 
https://github.com/DrKLO/Telegram/search?l=Java&q=UpdateContactsMessage

is the code to wrap with an if

**Comment by zarEclEC** [comment]
I did a commit 
https://github.com/ArmeF97/Telegram/commit/d76fc2d842e59a1593ecd1a8fde95dbc12f43d5a
Feel free to take it

**Comment by 23rd** [comment]
> I did a commit
> [ArmeF97@d76fc2d](https://github.com/ArmeF97/Telegram/commit/d76fc2d842e59a1593ecd1a8fde95dbc12f43d5a)
> Feel free to take it

It does not work.

**Comment by zarEclEC** [comment]
Sorry, my bad. I'll let do this to you, I'm no expert

**Comment by 23rd** [comment]
Wondering is this still an issue?

**Comment by zarEclEC** [comment]
No, thank you
