### ISSUE TITLE
Remove ads

### ISSUE THREAD

**Issue by timber-they** [forkgram/TelegramAndroid#252]
Telegram seems to have introduced [ads](https://ads.telegram.org/). I don't want to have to pay for them to go away, so it'd be nice if it was possible to disable them in Forkgram.

**Comment by 23rd** [comment]
No.

**Comment by timber-they** [comment]
@23rd this is not helpful at all. Can you please elaborate on that decision? Does Forkgram even make money with those ads?

**Comment by araccaine** [comment]
@timber-they Simple answer: This would violate [Telegram's TOS](https://core.telegram.org/api/terms) meaning that this app would be blocked from accessing their API:

> 3.3. If your app allows accessing content from Telegram [channels](https://telegram.org/tour/channels), you must include support for [official sponsored messages](https://core.telegram.org/api/sponsored-messages) in Telegram channels and may not interfere with this functionality.
