### ISSUE TITLE
[bug] Music stops when recording

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#27]
If music is playing on any software I've tried (Vinyl, NewPipe, Vanilla, VLC), recording a voice message makes the music stop playing.
The option "Disable pause music when recording" in the debug menu **IS NOT WORKING**.

Device: Zuk Z2 Pro with AOSP Extended 6.5 (Android 9).
Forkgram v6.0.1 (19110).
On Telegram-FOSS (F-Droid version) 6.0.1 no issue

Thank you

**Comment by 23rd** [comment]
If you want you can try [this version](https://github.com/Forkgram/TelegramAndroid/suites/628410622/artifacts/5063035). It should install as a regular update and fix your problem.

**Comment by ghost** [comment]
> If you want you can try [this version](https://github.com/Forkgram/TelegramAndroid/suites/628410622/artifacts/5063035). It should install as a regular update and fix your problem.

Thank you so much! Everything's fixed. Now the client is just perfect :)
