### ISSUE TITLE
[tracking] Microsoft AppCenter Crashes tracker

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#28]
I ran ClassyShark3xodus test on Forkgram. Is com.microsoft.appcenter.crashes tracker necessary?
I don't really see the point of having that inside a privacy-focused Telegram fork.
Telegram-FOSS on F-Droid doesn't have it.

**Comment by 23rd** [comment]
The AppCenter is the HockeyApp that was renamed recently.
HockeySDK has always been embedded into the official version.
This library is used only for the debug versions (all Forkgram releases are debug versions).
HockeySDK is used to deliver updates through their own feed and to receive crash reports.

So.
The official Telegram has the Play Market for updates.
The Telegram-FOSS has the F-Droid.
But I had nothing, so I used the embedded HockeySDK.
And when I released the first version of Forkgram, I just changed the hashes to mine.

After the last update (6.0.0) the HockeySDK was renamed and for some reason my automatic updates stopped working. So this library is now almost useless.

Currently I'm testing my own implementation of the auto updates via Github Releases, if it will be ok I'll remove the HockeySDK as the Telegram-FOSS did.
(Unfortunately, removing of the HockeySDK will make it difficult to fix my future bugs.)
