### ISSUE TITLE
[bug?] Can't see the account name from the drawer lateral menu

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#3]
The accounts names are replaced by three dots in the drawer menu. I don't understand if that's intentional or can be considered a bug. [Screenshot](https://i.imgur.com/aII58h5.jpg)

Version 5.4.0.7

**Comment by 23rd** [comment]
The phone is the device you use in public places. The idea was to hide sensitive and private data from prying eyes as much as possible (phone number and nicknames in the side menu, phone number, nickname and biography in the settings). For the same reason I added `Hide Title` in context menu of conversation.
I considered these changes do not impair the user experience. You can choose a second account, focusing on the avatar, and data changes in the settings are needed very rarely.

If you have any suggestions, I'm ready to listen.

**Comment by 23rd** [comment]
Perhaps I should write a readme, but I can not find time for this. =(

**Comment by RememberTheAir** [comment]
Oh, I understand

**Comment by RememberTheAir** [comment]
> Perhaps I should write a readme, but I can not find time for this. =(

https://telegra.ph/ff-06-04-2 did I miss something?

**Comment by 23rd** [comment]
You've written an almost complete list, thank you. I think I'll do readme now.

**Comment by RememberTheAir** [comment]
Btw, I've added "removed pencil floating icon" to the list based on 817aed20, but I can still see the floating pencil icon in my chats list. I'm not sure I understand what that commit is about

**Comment by 23rd** [comment]
Can you tell the steps to reproduce it?

**Comment by RememberTheAir** [comment]
Mmmh, I don't know. I just see the pencil icon, I thought it was removed

![image](https://user-images.githubusercontent.com/16143208/58887837-a6c46680-86e6-11e9-8a1b-804743a28bae.png)

**Comment by 23rd** [comment]
Hmm.
If you restart application or scroll down, it will be hidden. And it is hidden for me and I dont know how to reproduce it. =(

**Comment by RememberTheAir** [comment]
This is how it behaves on my phone: the pencil icon never reappears after getting hidden during scrolling. But when you open the app its gets back until you hide it again by scrolling
