### ISSUE TITLE
[Bug?]Can't disable in-app proxy

### ISSUE THREAD

**Issue by Abrakian** [forkgram/TelegramAndroid#30]
Hi,
I tried to disable and delete both proxy but after a while when I reopen the app it shows that I'm connecting to the proxy again.
Is there a way to permeability disable them?

**Comment by Abrakian** [comment]
Permanently disable them *
Sorry for the typo.

**Comment by 23rd** [comment]
You can try [this version](https://github.com/Forkgram/TelegramAndroid/suites/642594186/artifacts/5393693).

**Comment by Abrakian** [comment]
It seems to be fixed in the newest update 6.1.1.0.
Thank you!
