### ISSUE TITLE
[PSA] Telegram 6.2 changed the quick share sheet's chats order

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#32]
As far as I remember, Forkgram modifies the order in which chats are listed in the in-app quick share menu. The Android app recently changed that, and now chats are sorted in this way:

1. saved messages
2. unarchived pinned chats
3. all your unarchived chats
4. archived pinned chats
5. all your archived chats

I believe Forkgram used this same chats order. This is just a reminder that Forkgram can remove its own modification to the upstream code since now they have been adopted by the official app too

**Comment by 23rd** [comment]
@RememberTheAir Can you check [this version](https://github.com/Forkgram/TelegramAndroid/suites/761866251/artifacts/7918207)?

**Comment by RememberTheAir** [comment]
Yes, it looks like everything's ok
