### ISSUE TITLE
[Feature Request] Show "group id" in group info

### ISSUE THREAD

**Issue by zarEclEC** [forkgram/TelegramAndroid#33]
Forkgram shows a private user's telegram id, in their information page.

I'd like to have the same information displayed for groups (and channels, and everything)

Let me know if I was clear, thanks

**Comment by 23rd** [comment]
You can check [this version](https://github.com/Forkgram/TelegramAndroid/suites/1274443966/artifacts/19672245).

**Comment by ghost** [comment]
The new feature works fine!
