### ISSUE TITLE
[Feature Request] Disable media preview

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#35]
On Telegram 6.2 media preview feature was added.
**This is so bad for privacy**, just think about having private content (and not just NSFW) openly shown in your Telegram homescreen.
It would be optimal, not only for privacy, 
but for performance and aesthetic purposes, to add a toggle to deactivate this tedious option.
Thanks for the attention.

**Comment by 23rd** [comment]
Please, check the latest version.

**Comment by ghost** [comment]
Woww you're so efficient! Thank you so much, works perfectly
