### ISSUE TITLE
[Feature Request] Original file names

### ISSUE THREAD

**Issue by tsiflimagas** [forkgram/TelegramAndroid#36]
It would be really handy to have files downloaded by their original names and not by random numbers. It would be nice if you added it either by default or in forkgram special settings.

**Comment by 23rd** [comment]
If you open the context menu on any file and tap on "Save to downloads", your downloaded file will have the original name.

**Comment by tsiflimagas** [comment]
@23rd well that's not ideal for me, since it would spam Downloads folder with a ton of files unrelated to the ones which are already there. That's why I'd like to have them in telegram folder. But even if it's not possible, no problem 🙂
