### ISSUE TITLE
[issue] "title" info not appearing

### ISSUE THREAD

**Issue by HitaloM** [forkgram/TelegramAndroid#38]
After upgrading to Telegram source 6.3.0 the word "info" that appears in the profile of users, groups, channels and bots disappeared.

The below will be shown an example...

1. Telegram
![Telegram](https://telegra.ph/file/5a46b70fc2e3bcc9b8a5d.jpg)

2. Forkgram
![Forkgram](https://telegra.ph/file/eead10adccbbd5702259e.jpg)

**Comment by 23rd** [comment]
Yes, I have fixed this one, but I do not want to release new versions too often, so you can check fixed apk [here](https://github.com/Forkgram/TelegramAndroid/suites/1274443966/artifacts/19672245).

**Comment by ghost** [comment]
Now it works! You can close the issue
