### ISSUE TITLE
[BUG] Fullscreen profile pictures

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#39]
Until 6.2.0.3 I was able to see the profile pictures in fullscreen by long-tapping the picture. Now I can't.

Is it possible to restore the feature?

Edit: On Telegram 6.3 the feature is not missing

**Comment by ghost** [comment]
This is the old result of long-tapping on the profile picture, which no longer works.
![Screenshot_20200801-100535_Telegram_FOSS](https://user-images.githubusercontent.com/63900993/89097368-a30d9c00-d3de-11ea-8b24-43569514d39b.png)

This is the "normal" visualization, which still works in 6.3.
![Screenshot_20200801-100546_Telegram_FOSS](https://user-images.githubusercontent.com/63900993/89097369-a43ec900-d3de-11ea-8c2e-89977c5da3b5.png)

**Comment by ghost** [comment]
I noticed another related problem:
1) go to settings
2) long tap on personal profile picture
3) instead of showing the profile picture in full screen, a user info menu appears (change phone number / username / bio).

Maybe this is the source of the problem

**Comment by ghost** [comment]
The bug is still present on 7.1 and it's really annoying

**Comment by 23rd** [comment]
Are you sure you can open profile pictures in full screen mode in the official version?

**Comment by ghost** [comment]
100% sure, this is from version 7.0.1
![Screenshot_20201001-121419_UI_sistema](https://user-images.githubusercontent.com/63900993/94796883-ac67b480-03df-11eb-9208-b9fbd5f905dd.png)

**Comment by ghost** [comment]
I've asked a friend of mine who has non-FOSS version of 7.1.0, it works

**Comment by 23rd** [comment]
Yeah, I found the problem, thank you for your report. I think I'll release a new version in hour.

**Comment by ghost** [comment]
Thank you! You never let us down, you are the best @23rd

**Comment by ghost** [comment]
Now it's fixed. Thanks!
