### ISSUE TITLE
[feature request] option to make the quick share chats list the default way of selecting the receiver(s) of a forwarded message

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#4]
I've been using Telegram X for the past year and one design choice I think it nailed is to always use the quick share menu when forwarding something. Why I think it's much better than picking the chat from the classic chats list:

- it shows much many chats as soon as you open it, without having to scroll. It's easier to find a chat in a glance
- the chats are easier to reach. You don't have to stretch your thumb to reach the top of your screen
- the search icon is much easier to reach, for the same reason
- you can quickly add a comment to the medias you share
- you can easily select multiple chats and it is easier to see which chats you have selected
- it's harder to read your chats' names for people around you when you are in public places

It would be nice to have an option to always use it or make it the default sharing view when forwarding a message

**Comment by 23rd** [comment]
@RememberTheAir I replaced `Anonymous Forward` button in context menu with `Share` button. What you think?

**Comment by RememberTheAir** [comment]
It's ok imo. Efficient enough. This issue can be closed
