### ISSUE TITLE
[Bug?] Push notification

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#41]
**Device:** Zuk Z2 Pro (z2_row)
**Android version:** Pie (AOSP Extended 6.5 with microG)
**Forkgram version:** 7.1.3.0

I'm not receiving any notification since last update. I've tried everything, from removing battery optimization to reboot, but still I don't get any notification even though the "push service: tap to learn more" notification is there. Am I the only one?

Edit: Yes I'm going to try Telegram FOSS on F-Droid as soon as it's out.

Edit 2: No such issues on Telegram FOSS.

**Comment by Abrakian** [comment]
Notification is working perfectly fine here.

Pixel 3 with Android 9 + latest Forkgram

Maybe you should try reinstalling it.

**Comment by ghost** [comment]
I have updates. As time passed after a dirty reinstall, notifications started to work better. Now the problem ia that some of them are not shown while being counted. What I mean is that I can read in the top part notification i.e. "5 new messages from 2 chats", but I only get to see the preview for the very last message of one single chat.

**Comment by smirnov-tk** [comment]
Having the same issue after update (don't remember which version was ok)

Sometimes notifications working well, but usually they don't work at all and when I open app manually, lot's of chats gets loaded and I see new unread messages.

OnePlus 8 Pro, Android 10.5.10, Forkgram 7.1.3.0 (21000)

**Comment by 23rd** [comment]
Hmm, perhaps I broke something. I'll check it later.

**Comment by ghost** [comment]
The update fixed everything for me. What about you @smirnov-tk ?

**Comment by ghost** [comment]
It seems that updating (also without uninstalling) to 7.2.0.0 or 7.2.1.1 fixes the bug
