### ISSUE TITLE
[bug] "forward as album" always showing up in scheduled messages

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#43]
Steps to reproduce:

1. schedule a text message
2. open the chat's scheduled messages
3. select the message

**Current behavior**: after you select the message, the "forward as album" option appears in the bottom bar. If you try to use it, Forkgram asks you to select a destination chat, but nothing happens when you send it (no message is sent, which is expected)

**Expected behavior**: the option never show up in scheduled messages

Forkgram version: 7.2.1.7

![image](https://user-images.githubusercontent.com/16143208/99373763-166de780-28c2-11eb-9981-1586b0649aa5.png)

**Comment by 23rd** [comment]
Should be fixed.

**Comment by ghost** [comment]
@23rd I had this bug too, now it's fixed

**Comment by RememberTheAir** [comment]
Yes, it's no longer an issue
