### ISSUE TITLE
Build and distribute release apks

### ISSUE THREAD

**Issue by xeruf** [forkgram/TelegramAndroid#46]
I just downloaded your apk and inspected it out of curiosity - apparently, you are distributing Beta builds:
```sh
❯ aapt dump badging ForkClient\ 7.3.0.0.apk | grep package
package: name='org.forkclient.messenger.beta' versionCode='219509' versionName='7.3.0.0' compileSdkVersion='30' compileSdkVersionCodename='11'
```

Are you aware of that? It would be more appropriate to distribute release builds.

**Comment by 23rd** [comment]
Yes, I made that decision in the beginning. Back then, two years ago, this made it easy for me to do auto-updates.
Now I use my own "update system" via Github Releases, but there doesn't seem to be much reason to build release versions.
At least every current user would have to reinstall the application with the loss of their profile.

**Comment by DI555** [comment]
i would suggest making f-droid builds as release builds, the same way like the telegramfoss does..., with different app name without 'beta' words!

so, as benefit, could be possible using second installed copy!!!

**Comment by 23rd** [comment]
https://f-droid.org/en/packages/org.forkgram.messenger/

**Comment by Younes-L** [comment]
awesome ! congrats :partying_face:
