### ISSUE TITLE
[feature request] do not show last seen dots for users who do not share their last seen with you

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#48]
I find forkgram's feature of showing user's "online dot" with a different color based on their last seen time pretty cool.

Anyway, it would be nice if the dot was hidden with users who do not share your last seen with you, to keep the chats list cleaner. Or to show a grey one only when an user's last seen is "more than one week ago". This way the colored dots will be actually meaningful since they will give a proper and certain information about the user, and will be more noticeable since you won't see a lot of dots from people who have their last seen hidden

**Comment by RememberTheAir** [comment]
Just updated to 7.4 and it looks like it works like that. Thanks!

**Comment by 23rd** [comment]
Oh... But I did not do anything...

**Comment by RememberTheAir** [comment]
lmao. Maybe it always worked like that and I'm just stupid?

**Comment by derivativeoflog7** [comment]
Hijacking this old issue to ask, are the colours of the dots documented somewhere? I can't find anything

**Comment by 23rd** [comment]
Yellow dot — last seen <15 minutes ago.
Orange dot — last seen <30 minutes ago.
Red dot — last seen <60 minutes ago.
