### ISSUE TITLE
Battery drain fix and feature request

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#49]
I had an issue with battery drain and saw recently it fixed at Telegram FOSS repository. Can you merge the fix?

https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/237b86a510ca4d05f49c180308863afd003809d8

Also, can you add possibility to choose app and notification icon between original and forkgram's one?

**Comment by 23rd** [comment]
Oh, thanks a lot. I have not checked if this commit fixes the problem with battery, but I hope it does.

> Also, can you add possibility to choose app

I'm not really sure that it is possible to add pickable application icons. As far as I know you can change icons with third party solutions e.g. launchers or applications.

**Comment by ghost** [comment]
Thank you too. 

> I'm not really sure that it is possible to add pickable application icons.

Okay, I'll try to change icons and build myself then because I want to change notification icon and don't know how can I do it by another apps.

**Comment by 23rd** [comment]
By the way, following a quote from the official readme file.
> Kindly **do not** use our standard logo (white paper plane in a blue circle) as your app's logo.

**Comment by afwn90cj93201nixr2e1re** [comment]
@23rd any contact emails? I tried to ask around for your tg account but ended up with nothing. Hm, now I think that I could use some random repo (new organization + new repo to not link my profile to organization) issues tracker as I did in past. Ok.
