### ISSUE TITLE
Telegram checks only the first 10 digits of a phone number for duplicates

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#5]
Steps to reproduce:

- login with a phone number
- try to login with another phone number which is the same phone number you already used _but_ with another digit at the end

### Expected behavior

You can login with the 11-digits phone number and Telegram will not tell you the account is already registered

### Actual behavior

Telegram tells you the account is already registered, while you're actually logging in with a different phone number/account

### Example

I have some accounts that I registered with my phone number plus an additional digit at the end.

For example, I might have the following accounts:
- +39 1234567890 (10 digits)
- +39 12345678901 (11 digits)
- +39 12345678905 (11 digits)

On Telegram, right now, I am not able to login with the 11-digits accounts because apparently the app checks for duplicates only the first 10 digits of the number ([screenshot](https://i.imgur.com/1I0bevl.jpg))

I'm aware this is also an upstream issue but they apparently don't care to fix it. All the other clients don't have any issue with 11-digits "duplicate" accounts

Version 5.4.0.7

**Comment by 23rd** [comment]
Can you please make a screenshot with English? =(

Also you can embed it via ctrl+v instead of using Imgur.

**Comment by RememberTheAir** [comment]
![image](https://user-images.githubusercontent.com/16143208/55145047-4b07bb00-5142-11e9-8042-373e3b2df621.png)

**Comment by 23rd** [comment]
Thanks, I'll check it later.

**Comment by 23rd** [comment]
> All the other clients don't have any issue with 11-digits "duplicate" accounts

What other clients you have used?

**Comment by RememberTheAir** [comment]
I have tried with Telegram X and Telegram Desktop. My statement ("_All the other clients don't have any issue with 11-digits "duplicate" accounts_") was not completely correct btw, because Telegram Desktop doesn't support multiaccount so there isn't such a thing as "duplicate accounts" (I can login with 11-digits number on tdesktop btw). Telegram X doesn't warn you if I login with 11-digits accounts that share the first 10 digits with an already logged-in account. As far as I know, Telegram for MacOS behaves in the same way

**Comment by 23rd** [comment]
Fixed with ee7e0f098f84c0a5916be643c2fecc4c3d63be1a.
