### ISSUE TITLE
Remove Google Play censorship of channels

### ISSUE THREAD

**Issue by h1v9** [forkgram/TelegramAndroid#53]
As title says, please remove the censorship of channels requested by Google Play.
Really no reason to keep it since the app is not distributed on the Play Store.

**Comment by 23rd** [comment]
Do you have an example of such channels?

**Comment by h1v9** [comment]
The channel I'm talking about does not have a username so I don't know how to send it to you.

However, I found these examples:
https://www.newsbytesapp.com/news/science/telegram-offers-direct-download-citing-google-censorship/story

https://www.reddit.com/r/Android/comments/mqo5ac/telegram_now_offering_direct_download_for_android/guhqao0/

**Comment by RememberTheAir** [comment]
If forkgram is built as a debug build, client-side restrictions are disabled

**Comment by h1v9** [comment]
That may be a solution but running a debug build is not ideal.
I tried searching where the censorship is in the code but couldn't find it. Do you where it is?

**Comment by iamtherobin** [comment]
I am here to request the removal of censorship from Fork Client as well.

Here is an example of a blocked channel: https://t.me/invictusmaneo2077

I can view it on Desktop Client, NekoX android client and even Telegram Foss android client. If I try to view it in Fork Client android client, I am presented with this popup:
<a href="https://imgur.com/izliVI5"><img src="https://i.imgur.com/izliVI5.jpg" title="source: imgur.com" /></a>

The channel in question is the one middle one shown in the back ground. So it does show up in the channel list but will not open in Fork Client.

**Comment by 23rd** [comment]
Should be fixed now.

**Comment by iamtherobin** [comment]
Confirmed working now. Thanks.
