### ISSUE TITLE
menu for translate

### ISSUE THREAD

**Issue by franco27** [forkgram/TelegramAndroid#56]
hello

in conversations, I wish I could translate

**Comment by 23rd** [comment]
Now I think we can close this issue?

**Comment by franco27** [comment]
thank you for adding it
the Translate menu is only one way

**Comment by ruralTom** [comment]
Did this get added? I cannot find it

**Comment by franco27** [comment]
yes this menu has been added and both ways

**Comment by franco27** [comment]
go to settings and to language and you can enable translation

**Comment by ruralTom** [comment]
Thank you Sir.
