### ISSUE TITLE
[Visual] Chat themes are not applied to Forkgram-specific elements

### ISSUE THREAD

**Issue by CrisMystik** [forkgram/TelegramAndroid#57]
**Steps to Reproduce:**
* Open a private chat
* Set a Chat Theme
* Click on "..."

**Expected Behaviour**
Icons for Forkgram options such as "Hide title" should have the same color as the others

**Actual Behaviour**
Icons for these options are different than the others (they seem to follow global theme)

**Screenshot**
![IMG_20210921_181132_359](https://user-images.githubusercontent.com/62919067/134207371-05626915-a1f1-4d70-b79d-686772da113c.jpg)

**Comment by 23rd** [comment]
Thanks!

**Comment by 23rd** [comment]
Should be fixed now.

**Comment by CrisMystik** [comment]
> Should be fixed now.

Yes, I tried now
