### ISSUE TITLE
"Scan QR" option not available

### ISSUE THREAD

**Issue by CrisMystik** [forkgram/TelegramAndroid#58]
## Steps to Reproduce
1. Open Settings > Devices
2. **Scan QR** option is not shown

## Reason
Probably because the app uses a Desktop API ID, so `qr_login_camera` (from `help.getAppConfig()`) is disabled.

## Possible Solution
Ignore this configuration value

**Comment by 23rd** [comment]
Hmm, didn't pay attention to that condition, since I always had that "Scan QR code" button.

**Comment by 23rd** [comment]
I have removed that condition, does it have any effect for you?

**Comment by CrisMystik** [comment]
> I have removed that condition, does it have any effect for you?

Yes, now that option is displayed
