### ISSUE TITLE
[Bug] Wrong hour when forwarding from users with privacy

### ISSUE THREAD

**Issue by CrisMystik** [forkgram/TelegramAndroid#59]
## Steps to Reproduce
1. Open any chat
2. Forward a message from a user, that disabled link on forwarded messages, in any chat
3. Date on forward header is wrong

## Workaround
Exit and reopen the chat, the date is now correct

## Note
Probably this is correlated with TAndroid bug where forwarding a message from a user that disabled linking, the name is still clickable (**Workaround** also applies to this)

## Screenshot
![IMG_20211031_131444_397](https://user-images.githubusercontent.com/62919067/139582753-242f3499-5120-4ea2-ba10-5af46e65814e.jpg)

**Comment by 23rd** [comment]
> Probably this is correlated with TAndroid bug where forwarding a message from a user that disabled linking, the name is still clickable

I have fixed both of bugs.

**Comment by CrisMystik** [comment]
> > Probably this is correlated with TAndroid bug where forwarding a message from a user that disabled linking, the name is still clickable
> 
> I have fixed both of bugs.

Thanks, I tried now and can confirm they're completely fixed

**Comment by CrisMystik** [comment]
now it's crashing sometimes when forwarding a message though, also for some reason I can't click on my name in forward header (even if it's shown in bold)

**Comment by 23rd** [comment]
Maybe it will be better in the latest version.

**Comment by 23rd** [comment]
I have found another crash.
