### ISSUE TITLE
[bug?] Locations' map doesn't display

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#6]
Hello,

I just noticed that, when opening a location, the map doesn't load.

I'm aware that map previews has been an hot topic and in the past months there has been many changes in upstream due to Google's api keys and stuffs.

I think it's probably a known issue?

[Screenshot of the location in the chat](https://i.imgur.com/AYsEkih.jpg) (which works correctly), [screenshot of the location once opened](https://i.imgur.com/KFScFpY.jpg) (sorry for the Imgur urls but I'm from mobile)

**Comment by 23rd** [comment]
Map workaround was taken from Telegram FOSS.
Seems like it has same problem. =(

**Comment by 23rd** [comment]
@RememberTheAir It should be fixed now. Please check the latest version.

**Comment by RememberTheAir** [comment]
Seems to be working now, thanks
