### ISSUE TITLE
Forkclient crashing suddenly

### ISSUE THREAD

**Issue by iamtherobin** [forkgram/TelegramAndroid#60]
This morning I was using fork client just fine browsing some channel feeds. Then in the evening, I clicked an notification and it just crashed as soon as the window opened. It restarted immediately in the background and appeared to be working fine in the background but work crash as soon as I opened the window.

I tried clearing the cache and even reinstalling the app. The background notification works and the storage management window can be access from the app information screen in android. But as soon as I bring up the app window, it crashes immediately.

My phone is OnePlus3 running android 11 by crDroid. Here is the crash log: https://paste.crdroid.net/jtaSkp

I have temporarily had to moved to NekoX until this is figured out.

**Comment by 23rd** [comment]
Sorry, that was my fault. Now it should be fine.

**Comment by iamtherobin** [comment]
Thanks, it is working again. I assume it was something to due with the auto update being changed server side (guessing based on what I see in the logs)?

Can you make a modification to the client so it won't crash like that in the future when there is a similar issue?

**Comment by 23rd** [comment]
Yes, you're right, that should be fixed.
This night I added a blank release for testing and completely forgot about auto-updates.
I apologize for the inconvenience. =(

**Comment by 23rd** [comment]
I hope now it should be slightly better.
