### ISSUE TITLE
[Feature request] Delete all your messages

### ISSUE THREAD

**Issue by Ratemi** [forkgram/TelegramAndroid#61]
Hi! Thanks for your great fork. Can you add this function of delete all our messages from one chat? Like in NekoX

![Screenshot_20211109-171300_Nekogram_X](https://user-images.githubusercontent.com/75515427/140998362-cf8dc7ef-d108-4447-907f-60fb95854f02.png)

![Screenshot_20211109-171309_Nekogram_X](https://user-images.githubusercontent.com/75515427/140998429-d812b886-9771-435f-8aef-e268d71b11ba.png)

Thanks again! God bless you.

**Comment by RememberTheAir** [comment]
has been discussed in #19, maybe we should re-open that issue, if things changed

btw relevant commits that someone might pick up and cherry-pick:
- [`df1ec9d5c60949a8455ce34f36039e88ed9758d4`](https://github.com/NekoX-Dev/NekoX/commit/df1ec9d5c60949a8455ce34f36039e88ed9758d4)
- [`03dee963ce4b7ea14aac63275a25ac5be68c2b5f`](https://github.com/NekoX-Dev/NekoX/commit/03dee963ce4b7ea14aac63275a25ac5be68c2b5f)
- [`748ac2252da8e19b15042406c54f5ac415477a9a`](https://github.com/NekoX-Dev/NekoX/commit/748ac2252da8e19b15042406c54f5ac415477a9a)

**Comment by 23rd** [comment]
Yes, since then I have learned that things become easier with Kotlin.
So I tried to bring this feature for you.
The draft is ready at the link: https://github.com/Forkgram/TelegramAndroid/actions/runs/1447733766.
I would appreciate your feedback.

**Comment by RememberTheAir** [comment]
As far as I've been able to test, it works!

I tried to:

- delete all my messages from a normal group
- delete all my messages from a supergroup
- delete all my messages from a supergroup where the old chat history (before the conversion to supergroup) still had some of my messages

all of these tests worked correctly

(also thanks for asking for confirmation too times before actually executing the function)

**Comment by RememberTheAir** [comment]
Maybe the "dialog" word in "_Are you sure you want to delete all your messages from this dialog?_" should be replaced by "chat" or "group"

**Comment by DI555** [comment]
whould be great also to have possibility in that group's search: "show your massages" option !!!

**Comment by RememberTheAir** [comment]
It's already possible to filter only your messages, using the "👤" icon after selecting the "search" option

**Comment by DI555** [comment]
great than!
@23rd , could i ask for "show all messages" menu button after selecting one message?
so, could be possible to select message and see all messages of the owner(selected one owner)!!!
