### ISSUE TITLE
[feature request] option to hide the "send as" button in input box

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#62]
Telegram 8.3 introduced an option to post messages as one of the channels you own, in public groups and groups with a linked channel. If you don't own any channel you would ever use to post messages in public chats, this icon is an input box waste of space. I believe an option to hide that icon would be much appreciated :)

**Comment by 23rd** [comment]
Please check the latest version.

**Comment by RememberTheAir** [comment]
Awesome! Thank you :)
