### ISSUE TITLE
[Feature Request] Disable and hide the search icon

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#64]
Please add the option to disable search (on the home screen). I wouldn't want to see porn and drugs when searching, but I understand that it's impossible to filter it out.

**Comment by RememberTheAir** [comment]
I agree that Telegram has a big, massive problem with search results being often porn and disturbing content even when you search for perfectly normal names - but why hiding the search icon? You can just avoid to use it

**Comment by ghost** [comment]
In fact, I was looking for a family friendly alternative to Telegram, so that my child can only communicate safely with me, but due to the fact that there are not so many open source projects, I decided to ask ForkGram for this.

**Comment by 23rd** [comment]
> In fact, I was looking for a family friendly alternative to Telegram, so that my child can only communicate safely with me

Well, now the reasons are more clear to me. But I still think that hiding the search button is too radical solution. I assume you would be comfortable with an ability to disable the global search from settings.

Github CI has finished a job and you can download a test build from [here](https://github.com/Forkgram/TelegramAndroid/actions/runs/1674500293) (Artifacts section).
If it will be ok for you I'll keep this option.

**Comment by ghost** [comment]
Yes, this is exactly what I wanted, thank you very much

**Comment by 0xRustlang** [comment]
Thank you
This feature is great.

> > In fact, I was looking for a family friendly alternative to Telegram, so that my child can only communicate safely with me
> 
> Well, now the reasons are more clear to me. But I still think that hiding the search button is too radical solution. I assume you would be comfortable with an ability to disable the global search from settings.
> 
> Github CI has finished a job and you can download a test build from [here](https://github.com/Forkgram/TelegramAndroid/actions/runs/1674500293) (Artifacts section). If it will be ok for you I'll keep this option.
