### ISSUE TITLE
[Improvent] Please remove tab to navigate next/previous on media viewer

### ISSUE THREAD

**Issue by iamtherobin** [forkgram/TelegramAndroid#65]
Right now when viewing media, photos or video, tapping the screen will navigate next or previous media element depending on left or right side screen tap. This is concurrent with the swipe left/right gesture which makes tapping to navigate redundant.

However, the real issue it that is extremely annoying when I try to tap the hamburger icon, hide/show the overlay or scroll the playback bar and it changes the video to something else. It is driving me nuts.

Please disable tap to navigate. There is no need for it when we have swipe to navigate.

**Comment by 23rd** [comment]
To be honest I'm not sure I understand you correctly, can you provide any explaining screenshots?

**Comment by iamtherobin** [comment]
<a href="https://imgur.com/SFh3kIa"><img src="https://i.imgur.com/SFh3kIam.jpg" title="source: imgur.com" /></a><a href="https://imgur.com/bM8ACJX"><img src="https://i.imgur.com/bM8ACJXm.jpg" title="source: imgur.com" /></a>

I am talking about viewing media in full screen as shown  above. You can navigate next/previous media with a tap on left or right side of the screen or swipe the screen. The tapping interferes with trying to access the hamburger icon if I miss it, if I am trying to enable/disable the overlay or when I am trying to drag the position on the playback bar in videos.

**Comment by RememberTheAir** [comment]
Forkgram settings -> enable "Disable Flip Photos by Tapping"

**Comment by iamtherobin** [comment]
Sigh.... I went through all the telegram options looking for a way to disable that before posting and forgot Forkgram has it's own option menu. Thanks.

**Comment by 23rd** [comment]
Can be closed?
