### ISSUE TITLE
Why the 'tracks your activity' anti-feature on F-Droid?

### ISSUE THREAD

**Issue by Krusty27** [forkgram/TelegramAndroid#68]
I checked and the APK from F-Droid doesn't contain any tracker, why did they put this anti-feature on it?

**Comment by RememberTheAir** [comment]
I think it's explained [here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10036#note_806575059):

> > https://www.google.com/resolve?name=, https://dns.google.com/resolve?name= or https://mozilla.cloudflare-dns.com/dns-query?name=
> 
> As far as I know these urls have often been used in countries where Telegram was (or is) blocked.
Perhaps they can be replaced by open alternatives without any harm.

Reply from f-droid:

> Thanks to your explanations, I'm not sure whether that's needed. Are those DNS-URLs used automatically, without the user actively choosing – or are they rather options the user can choose from? In the latter case we won't need Tracking.

**Comment by Krusty27** [comment]
Uh okay, so nothing that scary. Thanks!
