### ISSUE TITLE
[bug?] chat's profile pictures don't display from the notifications

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#7]
Chats' icon/profile picture are not shown in the notification. I don't know if it's a bug or another measure to hide some sensitive information from those who can see your phone. If it's the latter, it would be nice to have an option to disable it, as my autistic brain sometime struggles to see the account's and chat's names to understand quickly what chat the notification is coming from :)

Screenshot:

![image](https://user-images.githubusercontent.com/16143208/55310905-ef9b3d00-5461-11e9-8f9c-a0df184dedf3.png)

**Comment by 23rd** [comment]
I cant reproduce your issue. I always had profile pictures in notifications.

**Comment by RememberTheAir** [comment]
This happens with upstream too, so it's not entirely related to Forkgram. Closing

**Comment by 23rd** [comment]
Oh, I recently updated my phone to the Android 9 and now I see the same problem.
Unfortunately, still dunno how to fix it. =(

**Comment by RememberTheAir** [comment]
Solved by re-installing
