### ISSUE TITLE
Fdroid Anti-Feature

### ISSUE THREAD

**Issue by nukelr** [forkgram/TelegramAndroid#70]
I've noticed that, on Fdroid, Forkgram is reported as having "Tracks and reports your activity" while this anti-feature is absent on Telegram FOSS. Why? What's the feature that made fdroid apply this "tag" on forkgram? 

https://f-droid.org/en/packages/org.forkgram.messenger/
https://f-droid.org/en/packages/org.telegram.messenger/

Thanks in advance

**Comment by Krusty27** [comment]
You can find an explanation here: #68

**Comment by nukelr** [comment]
Thank you very much!
