### ISSUE TITLE
[Bug] Crashes when receiving/starting a call

### ISSUE THREAD

**Issue by Krusty27** [forkgram/TelegramAndroid#72]
With version 8.5.4 (25660) from F-Droid, everytime I receive a call and click the green button the app crashes. Same thing when I call and the other person answers.

**Comment by Krusty27** [comment]
Is there a way I can provide some logs?

**Comment by 23rd** [comment]
Is it possible to check this problem in the build from Releases?

**Comment by Krusty27** [comment]
Yes it's different. It does not crash with the Github release (I don't know why)
