### ISSUE TITLE
Can we have more than Five pins pls?

### ISSUE THREAD

**Issue by ruralTom** [forkgram/TelegramAndroid#73]
Please Sir. I use the pins feature to put my favorite people up at the top of my list. Away from the commoners in my list. 😉

*edit* I can't mark this as a feature request

**Comment by 23rd** [comment]
`Fork Client Settings → Sync Pinned Dialogs`.

**Comment by ruralTom** [comment]
Ha! Perfect.  Thank you.

Mar 17, 2022 2:54:59 AM 23rd ***@***.***>:
