### ISSUE TITLE
hide this section from passcode in fork client setting

### ISSUE THREAD

**Issue by herotux** [forkgram/TelegramAndroid#74]
When check "hide this section from setting" in fork client passcode the section dosnt hide just move to top of menu .
![IMG_۲۰۲۲۰۳۲۴_۰۹۰۱۰۱](https://user-images.githubusercontent.com/10483351/159842649-14c7f7c9-2f85-40c2-a8d0-3c7f87292771.jpg)
![IMG_۲۰۲۲۰۳۲۴_۰۹۰۰۲۹](https://user-images.githubusercontent.com/10483351/159842652-fef1cffa-7de4-418b-86c3-0d74d5576c1d.jpg)

**Comment by 23rd** [comment]
Thank you for your report. This is my bad.
