### ISSUE TITLE
download Chrome ForkClient.8.6.2.0.apk - authorization required.

### ISSUE THREAD

**Issue by Klapautsiy** [forkgram/TelegramAndroid#75]
download Chrome ForkClient.8.6.2.0.apk - authorization required.  
![Screenshot_20220325-143121_Chrome](https://user-images.githubusercontent.com/34581168/160121928-01e5dc5d-1ac7-4fe3-bf1e-0b32053acfde.jpg)  

Android 10  

Chrome 99.0.4844.73  

where do I need to log in to download Fork Client.8.6.2.0.apk?

**Comment by 23rd** [comment]
Sorry, I don't know why Chrome requires an authorization. Anyway, every version can be found in Telegram channel and some latest of them can be found on F-Droid.
