### ISSUE TITLE
How to move from Telegram FOSS to Forkgram?

### ISSUE THREAD

**Issue by abdo2048** [forkgram/TelegramAndroid#76]
I have been using Telegram FOSS for a long time, but I uninstalled it and wanted to use Forkgram. I thought that when I insert the phone number in Forkgram, it will retrieve the data associate with this phone number, but instead it created a new account!
How to get back the old account?

I have the Official Telegram Desktop and signed in with the old account, will this help to migrate from Telegram FOSS to Forkgram?

**Comment by 23rd** [comment]
That's very weird. Are you sure you did not switch to test backend?

**Comment by abdo2048** [comment]
oops, I remembered now that I turned it on. What should I do? Uninstall and install it again without test backend on?

**Comment by 23rd** [comment]
Log out and log in with unchecked test backend.

**Comment by abdo2048** [comment]
[Solved] Logged out, then re-login without test backend checked.
Thank you, I appreciate your great efforts. Keep it up.

**Comment by dm17** [comment]
Great to have found this potential telegram-foss replacement! Does anyone have a comparison list of privacy features that one has that the other does not?
See:
`Changes` - https://github.com/Telegram-FOSS-Team/Telegram-FOSS ( <=== does forkgram cover everything listed here, for example?)
vs 
`Privacy Features` - https://github.com/forkgram/TelegramAndroid

**Comment by 23rd** [comment]
@dm17 
You are free to read commits that was cherry-picked from Foss repository.
