### ISSUE TITLE
Special share icons hide forward comment

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#8]
**Steps to reproduce**:

1. use the direct share icon
2. select a chat
3. write a comment in the comments box

The two additional special share icons hide the input text:

![image](https://user-images.githubusercontent.com/16143208/58232649-5e966300-7d3a-11e9-9137-e37461a86f26.png)

**Comment by 23rd** [comment]
Any suggestions what to do with it?

**Comment by RememberTheAir** [comment]
Maybe letting the text slide to the left as soon as we get to the first icon

**Comment by 23rd** [comment]
@RememberTheAir Should be fixed in 5.7.1.1.

**Comment by RememberTheAir** [comment]
Looks ok to me. Closing
