### ISSUE TITLE
[Feature Request] Arch based releases and Gcm version

### ISSUE THREAD

**Issue by invinciblevenom** [Forkgram/TelegramAndroid#80]
It would be really helpful if we have releases based on the arch(arm64-v8a, armeabi-v7a, etc.). Also we can have a Gcm(Google Cloud Messaging) push service used by original Telegram App.

**Comment by invinciblevenom** [comment]
Both these features will require some code in the workflow file. We can see the example of [https://github.com/NekoX-Dev/NekoX/blob/main/.github/workflows/release.yml](NekogramX)

**Comment by 23rd** [comment]
> It would be really helpful if we have releases based on the arch(arm64-v8a, armeabi-v7a, etc.).

Why do you need them?

**Comment by invinciblevenom** [comment]
> > It would be really helpful if we have releases based on the arch(arm64-v8a, armeabi-v7a, etc.).
> 
> Why do you need them?

It's not really necessary as such but can be an option for different users

**Comment by 23rd** [comment]
I purposely did not make separate builds, as the current builds work fine on both old and new versions of Android.
That's why I don't see any reason to complicate the workflow.

**Comment by 23rd** [comment]
> Also we can have a Gcm(Google Cloud Messaging) push service used by original Telegram App.

I will never will do this.
You are free to make your own builds with GCM or to use another forks. You will not find GCM here.

**Comment by invinciblevenom** [comment]
Thanks!
