### ISSUE TITLE
missing default icon [8.8.2.0]

### ISSUE THREAD

**Issue by repsorp** [forkgram/TelegramAndroid#87]
Default icon is missing...

![Screenshot_20220621-172243.png](https://user-images.githubusercontent.com/6297032/174837954-7dc1118d-6490-4419-8281-aa31f7564ddd.png)

**Comment by gcvl** [comment]
Confirmed. I switched to the ocean variant icon from Chat Settings, it's fine.

**Comment by 23rd** [comment]
Oh...

**Comment by 23rd** [comment]
Can you share your Android version?

**Comment by repsorp** [comment]
> Can you share your Android version? 

Android 12
Same issue with Android 11

**Comment by 23rd** [comment]
Perhaps it will be better in 8.8.3.0.

**Comment by repsorp** [comment]
> Perhaps it will be better in 8.8.3.0.

It has, thanks
