### ISSUE TITLE
Drawe header color doesn't match theme's header coler

### ISSUE THREAD

**Issue by RememberTheAir** [forkgram/TelegramAndroid#9]
The error can be reproduced by setting a custom theme with a different header color. The sidebar header doesn't change its color and stays blue

![image](https://user-images.githubusercontent.com/16143208/61529626-20f44480-aa22-11e9-8d10-1fe217f4d2a6.png)

**Comment by RememberTheAir** [comment]
Wrong: it changes after witching account or closing the app

**Comment by 23rd** [comment]
Unfortunately, I'm switching themes and can't reproduce issue.
Did you try the same pattern in official client?

**Comment by RememberTheAir** [comment]
I believe the standard app shows you your background image there

**Comment by RememberTheAir** [comment]
> I believe the standard app shows you your background image there

Nvm it doesn't.

By the way, I can't reproduce the issue, it happens rarely. I've almost been able to reproduce it on the standard app from a tablet - but it happened differently (leave telegram while a chat is open, re-open Telegram: it shows the default header color on the top chat title bar)

**Comment by RememberTheAir** [comment]
Doesn't seem to happen anymore. Will reopen if the issue persists
