### ISSUE TITLE
Is it possible to add custom title support in launcher?

### ISSUE THREAD

**Issue by ghost** [forkgram/TelegramAndroid#91]
![IMG_20220630_191223.jpg](https://user-images.githubusercontent.com/108591373/177014680-3fa39102-cf8b-43a6-9462-a0e22318cb30.jpg)![IMG_20220630_191000.jpg](https://user-images.githubusercontent.com/108591373/177014684-e3528b41-c4c0-4742-9f48-259a0f66d464.jpg)

**Comment by 23rd** [comment]
I believe it can be done with launcher in your OS.

**Comment by ghost** [comment]
> I believe it can be done with launcher in your OS.

Hm 👍🏼
